### ISSUE TITLE
Sauvegarder ses playlists sur internet

### ISSUE THREAD

**Issue by PeterPanCake** [Bludwarf/cuetube#106]
Pour transmettre les playlistes sur d'autres PC

**Comment by Bludwarf** [comment]
https://developers.google.com/drive/v3/web/about-sdk

**Comment by Bludwarf** [comment]
OK pour la connexion écriture/lecture sur Google Drive.
RAF : synchro avec la persistance précédente

**Comment by Bludwarf** [comment]
Salut Julia, ça farte ?
C'est fini pour pouvoir sauvegarder ses collections sur Google Drive. Pour l'instant c'est un peu lent mais ça viendrait avec les versions suivantes !
Bises

**Comment by PeterPanCake** [comment]
Trop super ! Bien joué !


________________________________
De : Mathieu Lavigne <notifications@github.com>
Envoyé : mardi 13 février 2018 08:23
À : Bludwarf/cuetube
Cc : PeterPanCake; Author
Objet : Re: [Bludwarf/cuetube] Sauvegarder ses playlists sur internet (#106)


Salut Julia, ça farte ?
C'est fini pour pouvoir sauvegarder ses collections sur Google Drive. Pour l'instant c'est un peu lent mais ça viendrait avec les versions suivantes !
Bises
