### ISSUE TITLE
Import de tracklist à partir d'un commentaire avec saut de ligne

### ISSUE THREAD

**Issue by PeterPanCake** [Bludwarf/cuetube#107]
Les sauts de ligne sont mal gérés depuis un commentaire (ils sont virés)

**Comment by Bludwarf** [comment]
Uniquement avec Firefox et uniquement depuis un commentaire

**Comment by Bludwarf** [comment]
Hélas c'est un bug de Firefox :'(
https://bugzilla.mozilla.org/show_bug.cgi?id=1174452

**Comment by PeterPanCake** [comment]
Trop swagg mec !! Cimer !


________________________________
De : Mathieu Lavigne <notifications@github.com>
Envoyé : mardi 19 décembre 2017 11:46
À : Bludwarf/cuetube
Cc : PeterPanCake; Author
Objet : Re: [Bludwarf/cuetube] Import de tracklist à partir d'un commentaire avec saut de ligne (#107)


Closed #107<https://github.com/Bludwarf/cuetube/issues/107>.

**Comment by Bludwarf** [comment]
Ben merci surtout à toi qui est ma 1ère utilisatrice ;)
J'ai ajouté la lecture en boucle comme tu me disais que ça pouvait être pratique !
